openapi: 3.0.1
components:
  schemas:

    Critical:
      description: "Enumeration contains identifiers determining the critical feature of the security element"
      type: integer
      enum:
        - 0
        - 1
      x-enum-descriptions:
        - "Security element could not be present in a valid document"
        - "Security element must be present in a valid document"
      x-enum-varnames:
        - "NOT_CRITICAL"
        - "CRITICAL"