openapi: 3.0.3
components:
  schemas:

    SecurityFeatureType:
      description: "Enumeration contains identifiers determining types of features for a document authenticity checking"
      type: integer
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
      x-enum-description:
        - "Blank element"
        - "Personalization element"
        - "Photo"
        - "MRZ"
        - "Photo surrounding area"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Reserved for internal use"
        - "Main portrait and ghost portrait comparison"
        - "Main portrait and RFID portrait comparison"
        - "Main portrait and other page portrait comparison"
        - "Barcode format check"
        - "Different lines thickness"
        - "Portrait comparison with image from camera"
        - "Portrait comparison with image from RFID"
        - "Ghost photo"
        - "Clear ghost photo"
        - "Invisible object"
        - "Low contrast object"
        - "Photo color type"
        - "Photo squareness check"
        - "Photo corners shape"
        - "Cancelling document"
        - ""
        - ""
        - ""
      x-enum-varnames:
        - "BLANK"
        - "FILL"
        - "PHOTO"
        - "MRZ"
        - "FALSE_LUMINESCENCE"
        - "HOLO_SIMPLE"
        - "HOLO_VERIFY_STATIC"
        - "HOLO_VERIFY_MULTI_STATIC"
        - "HOLO_VERIFY_DYNAMIC"
        - "PATTERN_NOT_INTERRUPTED"
        - "PATTERN_NOT_SHIFTED"
        - "PATTERN_SAME_COLORS"
        - "PATTREN_IRI_INVISIBLE"
        - "PHOTO_SIZE_CHECK"
        - "PORTRAIT_COMPARISON_VS_GHOST"
        - "PORTRAIT_COMPARISON_VS_RFID"
        - "PORTRAIT_COMPARISON_VS_VISUAL"
        - "BARCODE"
        - "PATTERN_DIFFERENT_LINES_THICKNESS"
        - "PORTRAIT_COMPARISON_VS_CAMERA"
        - "PORTRAIT_COMPARISSON_RFID_VS_CAMERA"
        - "GHOST_PHOTO"
        - "CLEAR_GHOST_PHOTO"
        - "INVISIBLE_OBJECT"
        - "LOW_CONTRAST_OBJECT"
        - "PHOTO_COLOR"
        - "PHOTO_SHAPE"
        - "PHOTO_CORNERS"
        - "DOCUMENT_CANCELLING_DETECTOR"
        - "PORTRAIT_COMPARISON_EXT_VS_VISUAL"
        - "PORTRAIT_COMPARISON_EXT_VS_RFID"
        - "PORTRAIT_COMPARISON_EXT_VS_LIVE"