openapi: 3.0.1
components:
  schemas:

    OCRSecurityTextResult:
      allOf:
        - $ref: '../rt-authenticity.yml#/components/schemas/AuthenticityCheckResultItem'
        - type: object
          properties:
            CriticalFlag:
              $ref: './e-critical.yml#/components/schemas/Critical'
            LightType:
              $ref: '../common.yml#/components/schemas/Light'
            FieldRect:
              $ref: '../common.yml#/components/schemas/RectangleCoordinates'
            EtalonResultType:
              type: integer
            EtalonFieldType:
              type: integer
            EtalonLightType:
              type: integer
            SecurityTextResultOCR:
              type: string
            EtalonResultOCR:
              type: string
            Reserved1:
              type: integer
            Reserved2:
              type: integer